<?php

namespace AppBundle\Repository;

/**
 * ManifestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManifestationRepository extends \Doctrine\ORM\EntityRepository
{
}
